
export const assetsMapping = {
  "address": "0xca581d8B13bD1CCf2dffcc9970A2d721a3db2dd4",
  "assets": [
    "abuse",
    "bang",
    "fire",
    "forever_alone",
    "froog",
    "fuuuu",
    "gangnam_style",
    "giggle_meme",
    "headshot",
    "laughing",
    "leosmug",
    "meow_meme",
    "bleh",
    "noice",
    "nood",
    "oh_no",
    "orange_smile",
    "pog",
    "really",
    "rip",
    "sad",
    "sick",
    "so_small",
    "boykisser",
    "stare_dad",
    "the_pain",
    "thumbs_down",
    "thumbs_up",
    "chicken_dinner",
    "clown",
    "clueless",
    "dog_thumb_down",
    "dont_care",
    "fart"
  ]
};